services:
  - name: service-a
    path: ./services/service-a
    language: dotnet
    base_urls:
      - http://service-a
      
  - name: service-b
    path: ./services/service-b
    language: dotnet
    base_urls:
      - http://service-b

  - name: service-c
    path: ./services/service-c
    language: dotnet
    base_urls:
      - http://service-c 

  - name: service-d
    path: ./services/service-d
    language: dotnet
    base_urls:
      - http://service-d

  - name: service-e
    path: ./services/service-e
    language: dotnet
    base_urls:
    - http://service-e

repositories:
  - name: Repo-0
    url: https://github.com/lokesh0507/Repo-0.git
    branch: main

  - name: Repo-1
    url: https://github.com/lokesh0507/Repo-1.git
    branch: main
 
  - name: Repo-2
    url: https://github.com/lokesh0507/Repo-2.git
    branch: main

  

  
 
external_endpoints: []