services:
  - name: service-a
    path: ./services/service-a
    language: dotnet
    base_urls:
      - http://service-a
      
 
  - name: service-b
    path: ./services/service-b
    language: dotnet
    base_urls:
      - http://service-b
 
external_endpoints: []